export const environment = {
  supabaseUrl: 'https://umrzmenylzqydjpyucvq.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcnptZW55bHpxeWRqcHl1Y3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MTE4MDIsImV4cCI6MjEwMzE4NzgwMn0.nNRtm2WQh_Mj0b0MVuWwpRB9XTshEuIBfxE4HpmTDrk'
};
